# Datentypen

## Basics

Was Python meiner Meinung nach sehr anfängerfreundlich macht, ist dass Python sehr flexibel ist was Datentypen angeht. Man muss nicht von vorne herein festlegen, welchen Datentyp man verwendet und Python konvertiert je nach Bedarf auch automatisch zwischen den verschiedenen Datentypen.<br>
Da die Details zu den basic Datentypen relativ egal sind, gehe ich direkt zu den komplexeren Datentypen über die Python hat.

## Listen
<b>Listen</b> sind ein sequenzieller Datentyp. Sie speichern einfach eine Abfolge an Einträgen, ähnlich zu einem Vektor. Einzelne Einträge können dann mit eckigen Klammern abgefragt werden.<br>
Wenn man den Eintrag <font color='green'>-1</font> abfragt, erhält man den letzten Eintrag der Liste. Will man eine bestimmte Subsektion aufrufen, kann man das mittels [s:e] machen

In [3]:
automarken = ["Mercedes", "Porsche", "Audi", "BMW"]
print(automarken[2])
print(automarken[-1])
print(automarken[2:4])

Audi
BMW
['Audi', 'BMW']


## Dictionaries

Wenn man bestimmte Kombinationen abspeichern will, kann man dies mittels sogenannten <b>Dictionaries</b> tun. Damit kann man mit dem <i>Key</i> einen <i>Value</i> aufrufen. Diese müssen im Allgemeinen auch keine fixe reihenfolge zueinander haben.

In [6]:
noten = {"Ex 1": 1.3, "Theo A": 4.0, "Ex b": 3.0, "Theo B": 5.0}
print(noten["Theo A"])
print(noten["Ex 1"])

4.0
1.3


## Praktische Hinweise

### numpy Arrays
Wir werden für sehr vieles numpy Arrays verwenden. Im Prinzip kann man diese genause wie Listen verwenden, man hat aber durch numpy mehr Möglichkeiten, mit ihnen zu rechnen und sie als richtige Vektoren, Matrizen oder Tensoren zu benutzen.

In [2]:
import numpy as np

a = np.array([1, 3])
b = np.array([3, 6])

# Skalarprodukt
print(a.T @ b)

A = np.array([[2,4], [3, 1]])
B = np.array([[3, 8], [1, 5], [4, 9]])

# Matrixmultiplikation
print(A @ B.T)

# Broadcasting mittels vectorisation (braucht ihr wahrscheinlich nicht)
print(np.sum(A[:, None, :] - B[None, :, :], axis=1))

21
[[38 22 44]
 [17  8 21]]
[[ -2 -10]
 [  1 -19]]


### Befüllen von Listen

Man kann zwar eine komplette Schleife schreiben um eine Liste automatisch mit bestimmten Werten zu befüllen, Python bietet aber eine verkürzte Schreibweise dafür an.

In [13]:
a = [i for i in range(0, 10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Iterieren über Listen und Dictionaries

Python bietet auch die Möglichkeit über Listen und Dictionaries zu iterieren.

In [15]:
for marke in automarken:
    print(marke)
    
print("----------")

for key in noten:
    print(noten[key])

Mercedes
Porsche
Audi
BMW
----------
1.3
4.0
3.0
5.0
